### PR TITLE
Fixed Font reference usage in Text

### PR DESCRIPTION
**Pull request by rcmaniac25**
Fixed issue where Text would reference internal members of Font, and try to release them.
Release Font in SpriteSample.
Converted tabs to spaces in SpriteSample.

Fix for #1706

### CODE REVIEW

**Comment by seanpaultaylor** [comment]
Can you also make a pull request to master too ?

**Comment by seanpaultaylor** [comment]
Why do you need drawFont ?

**Comment by rcmaniac25** [comment]
Because Text directly accesses the internal sizes of Font. The parent Font ‎need to be released when Text is released.

This means I need the parent Font and an additional internal Font or Font can release the parent instead of itself, or delegating the Font to the directly sized Font should be ignored since every draw is going to find the nearestSizeFont.

Second one was too much of a change (if the destructor is being called on the child Font, it's dead already and will corrupt the parent regardless), last one would be easiest but means we're looking up the font each draw, and that left the first option of saving the draw font and the parent font.

From: Sean Taylor
Sent: Thursday, January 29, 2015 10:53 PM
To: gameplay3d/GamePlay
Reply To: gameplay3d/GamePlay
Cc: rcmaniac25
Subject: Re: [GamePlay] Fixed Font reference usage in Text (#1708)


Why do you need drawFont ?

---

**Comment by rcmaniac25** [comment]
Is the pull request good then or are there changes that I should make?

**Comment by seanpaultaylor** [comment]
I still don't see why you need to keep this _drawFont
You need to manage the correct addRef calls to simply use the _font

**Comment by rcmaniac25** [comment]
But if I call addRef on _font, and I replace _font with the internal, size-specific Font, how am I supposed to get the parent Font from the internal Font?

If you really don't want Text to have _drawFont, then I have 2 options:

1. I can modify Font to have a reference to it's parent font so I can release it when done.
2. I keep _font without delegating it to a size-specific Font, then it will just always look up the font size which is fine to me, but may be slow for drawing every frame.

**Comment by rcmaniac25** [comment]
I'll go do a master-branch version.

**Comment by seanpaultaylor** [comment]
Yes please. Only that one fix though. Not the encoder tmx stuff.

**Comment by rcmaniac25** [comment]
I know

**Pull request merged**
