### PR TITLE
Recognize .otf as .ttf files (the library supports them.)

### PR DESCRIPTION
**Pull request by jwatte**

### CODE REVIEW

**Comment by seanpaultaylor** [comment]
Have you tested this ?

**Comment by jwatte** [comment]
I used it on some otf files I have, and it worked fine.
I have not tested this individual commit in isolation, because i had a large number of commits to tease apart rather than dump 12 change lists in one pull request...

**Comment by jwatte** [comment]
Hmm. I wonder why Transform::getMatrix() is in that pull request? That was supposed to be in a separate request. Anyway, yes, those are also tested. The samples run fine.
A set of unit tests would make testing more thorough, but that doesn't seem to be the current modus operandi.

**Comment by jwatte** [comment]
Why not just merge both? I intend both changes to be submitted.

**Pull request closed without merging**
