### PR TITLE
opengl 4 for desktop

### PR DESCRIPTION
**Pull request by fredakilla**
Hi

I migrate opengl version from 3.1 to 4.3 on Windows desktop.

Main change is for MeshBatch to support hardware VAO. For that I use the reven86 code : https://github.com/reven86/GamePlay/commit/5231931144d60fc34c04f8f23c55f47480847523
and I completed it to support Indexed geometries (MeshPart). I made some conditionals compilation #ifdef to support backward compatibility (MeshBatch without VAO).

Tested with
- Windows 7  - nvidia GeForce GTX 670
- Windows 7  - ati 6480G
- Ubuntu 14.04  - nvidia GeForce GTX 670

### CODE REVIEW

**Comment by xthydra** [comment]
is it just me that doesn't understand the correlation between the variables "red" and "alpha" in his changes?

**Comment by fredakilla** [comment]
glTexImage2D return GL_INVALID_VALUE is GL_ALPHA is passed.

GL_ALPHA no longer exists for glTexImage2D in gl 4 (https://www.opengl.org/sdk/docs/man4/html/glTexImage2D.xhtml). So to use a single channel component (like in alpha case) we must use the red channel (GL_RED).

**Comment by xthydra** [comment]
Every samples seem to be working fine with your changes and i'm sorry for the previous question.

**Comment by fredakilla** [comment]
No problem it was a usefull question.

I tested deeply and fixed 2 bugs with previous push:

- the primitive type was missing for MeshBatch (ex: bad drawing on terrain + collision 3d samples with debug option activated)
- in old shaders (110) using red channel for alpha compuation can't be done. So I created a new fontgl4.frag shader and choosing which one at compil time)

**Pull request closed without merging**
