### PR TITLE
Updated VS2013 projects to use DirectX SDK default path.

### PR DESCRIPTION
**Pull request by seanpaultaylor**

### CODE REVIEW

**Comment by louis-mclaughlin** [comment]
Windows drive isn't guaranteed to be installed on the C drive, you can build the path using $(programfiles(x86))

**Comment by seanpaultaylor** [comment]
So you're saying replace "C:\Program Files (x86)" with "$(programfiles(x86))" in all the directx paths ?
If you can change them all and test/verify its working properly in vs2013, I will accept the change.
Otherwise I can try it tonight.

**Comment by louis-mclaughlin** [comment]
>So you're saying replace "C:\Program Files (x86)" with "$(programfiles(x86))" in all the directx paths ?

Yes

I can do this tonight (GMT)

**Comment by louis-mclaughlin** [comment]
#1697

**Pull request merged**
