### PR TITLE
Updated Building instructions

### PR DESCRIPTION
**Pull request by rcmaniac25**
Added VS2017 scripts

### CODE REVIEW

**Comment by seanpaultaylor** [comment]
Lets just update the existing system to vs2017 instead.

**Comment by qq910438219** [comment]
good,but I'd prefer to Qt Creator for smaller  size
(vs2017 downlaod link: https://www.visualstudio.com/zh-hans/downloads/ )

**Comment by rcmaniac25** [comment]
@seanpaultaylor Anything specific you want me to do? Or just take the 2017 script/instructions and make those the regular script/instructions?

**Comment by ghost** [comment]
@rcmaniac25 You'll also need to update the automated windows build (.appveyor.yml) to use 2017.

**Comment by rcmaniac25** [comment]
Ok, will do

**Comment by rcmaniac25** [comment]
The Mac builds aren't building properly in Travis, but I never touched any Mac parameters or configs...

**Comment by ghost** [comment]
You can ignore that, see https://github.com/gameplay3d/GamePlay/pull/1976

**Comment by rcmaniac25** [comment]
Ok

**Comment by seanpaultaylor** [comment]
Looks like travis-ci is failing. Might want to update to Qt 5.11 in instructions and build now too.

**Comment by rcmaniac25** [comment]
Yes. Will update on weekend

**Pull request closed without merging**
